services:
  postgres-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: my_measurements_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-net

  my-measurements-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./Backend/models:/app/models
      - ./Backend/uploads:/app/uploads
      - ./Backend/temp:/app/temp
    environment:
      DATABASE_URL: postgresql://postgres:123456@postgres-db:5432/my_measurements_db
    depends_on:
      - postgres-db
    networks:
      - my-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  my-measurements-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - my-measurements-backend
    networks:
      - my-net

volumes:
  postgres_data:

networks:
  my-net:
